version: '3.4'

services:

  db:
    image: mysql:5.7.22
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: teste
    ports:
      - "3308:3306"
    volumes:
      - type: bind
        source: ./DBBackup/backup.sql
        target: /docker-entrypoint-initdb.d/backup.sql
    networks:
      - teste


  sistema:
    image: ${DOCKER_REGISTRY-}sistema
    build:
      context: .
      dockerfile: Sistema/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:80"
    links:
      - db
    depends_on:
      - db
    networks:
      - teste

networks: 
    teste:
        driver: bridge
