FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY ["Sistema/Sistema.csproj", "Sistema/"]
RUN dotnet restore "Sistema/Sistema.csproj"
COPY . .
WORKDIR "/src/Sistema"
RUN dotnet build "Sistema.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Sistema.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Sistema.dll"]
